version: '3.7'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: php:latest
    container_name: 'php'
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.override.ini:ro
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    working_dir: '/var/www/html'
    restart: unless-stopped

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: nginx:latest
    container_name: 'nginx'
    volumes:
      - ./:/var/www/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    ports:
      - '80:80'
      - '443:443'
    hostname: 'nginx'
    restart: unless-stopped
